insert into "genres" ("name") values('Комедия');
insert into "genres" ("name") values('Драма');
insert into "genres" ("name") values('Мультфильм');
insert into "genres" ("name") values('Триллер');
insert into "genres" ("name") values('Документальный');
insert into "genres" ("name") values('Боевик');
insert into "ratings" ("name", "description") values('G','у фильма нет возрастных ограничений');
insert into "ratings" ("name", "description") values('PG','детям рекомендуется смотреть фильм с родителями');
insert into "ratings" ("name", "description") values('PG-13','детям до 13 лет просмотр не желателен');
insert into "ratings" ("name", "description") values('R','лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
insert into "ratings" ("name", "description") values('NC-17','лицам до 18 лет просмотр запрещён');
